version: "3.8"
services:

  quiz-api:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - APP_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./docker/mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}